version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=socialapp
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
    volumes:
      - /tmp/mysql:/var/lib/mysql
  web:
    build: .
    command: /usr/src/app/migrate_run.sh db
    environment:
      - DJANGO_SETTINGS_MODULE=docker_settings
      - DB_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis:5.0-rc-stretch
    hostname: redis
    ports:
      - "6379:6379"
  front:
    build:
      context: ../frontend/.
      dockerfile: ../frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - web
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
      - 443:443
    restart: always 


 
