# Generated by Django 2.1 on 2018-11-13 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='mentorship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mentorship', to='Mentorship'),
        ),
    ]
