# Generated by Django 2.1 on 2018-11-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification_mentorship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='linkedin_profile',
            new_name='linkedin',
        ),
        migrations.AddField(
            model_name='user',
            name='behance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube',
            field=models.TextField(blank=True, null=True),
        ),
    ]
